services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    # command: tunnel --config /etc/cloudflared/config.yml run
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    volumes:
      - ./cloudflared:/etc/cloudflared
    env_file:
      - .env
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true